# Format: dart format .
# Lint: dart analyze

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'
    - '.dart_tool/**'
    - '.github/**'
    - '.vscode/**'
    - '.idea/**'
    - 'output/**'  # 生成されたファイルを解析から除外
  language:
    strict-raw-types: true
  errors:
    todo: info  # TODOコメントをエラーではなく情報として表示
    avoid_print: ignore  # CLIツールで使用するprint文の警告を無視

linter:
  rules:
    avoid_print: false  # CLIツールでprint文を許可
    public_member_api_docs: false

    # コード複雑性の制限
    function_body_lines_limit: 50 
    class_member_lines_limit: 300
    file_lines_limit: 500       
    cyclomatic_complexity: 10    
    block_nesting_depth: 5      

# formatter設定
# 'dart format' コマンド使用時に適用
formatter:
  line_length: 120 
  indent: ['space', 2]
