name: app_icon_gen
description: A CLI tool to generate iOS/Android app icons from a single image
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  args: ^2.3.1
  image: ^4.0.17
  path: ^1.8.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
