name: App Icon Gen CI

on:
  push:
    branches: [ "master", "main" ] 
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # リポジトリをチェックアウト

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1  # Dart SDKをセットアップ
        with:
          sdk: 'stable'
          
      - name: Install dependencies  # 依存関係をインストール
        run: dart pub get
        
      - name: Set shell script permissions  # シェルスクリプトに実行権限を付与
        run: chmod +x app-icon-gen.sh
        
      - name: Verify formatting  # コードフォーマットをチェック
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze project source  # 静的解析を実行
        run: dart analyze
        
      - name: Run platform tests  # プラットフォーム別テストを実行
        run: dart test
        
  integration:
    name: Integration Tests
    needs: test
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
          
      - name: Install dependencies
        run: dart pub get
        
      - name: Set shell script permissions
        run: chmod +x app-icon-gen.sh
        
      - name: Verify iOS Icon Output
        run: |
          # iOSアイコン生成の検証
          ./app-icon-gen.sh -p ios assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/ios" ]; then
            echo "Error: iOS output directory was not created"
            exit 1
          fi
          
          # Contents.jsonのチェック
          if [ ! -f "output/ios/AppIcon.appiconset/Contents.json" ]; then
            echo "Error: iOS Contents.json was not created"
            exit 1
          fi
          
          echo "iOS icon generation: SUCCESS ✅"

      - name: Verify Android Icon Output
        run: |
          # Androidアイコン生成の検証
          ./app-icon-gen.sh -p android assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/android" ]; then
            echo "Error: Android output directory was not created"
            exit 1
          fi
          
          # mipmapディレクトリのチェック
          if [ ! -d "output/android/mipmap-mdpi" ]; then
            echo "Error: Android mipmap directories were not created"
            exit 1
          fi
          
          echo "Android icon generation: SUCCESS ✅"

      - name: Verify watchOS Icon Output
        run: |
          # watchOSアイコン生成の検証
          ./app-icon-gen.sh -p watchos assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/watchos" ]; then
            echo "Error: watchOS output directory was not created"
            exit 1
          fi
          
          # Contents.jsonのチェック
          if [ ! -f "output/watchos/AppIcon.appiconset/Contents.json" ]; then
            echo "Error: watchOS Contents.json was not created"
            exit 1
          fi
          
          echo "watchOS icon generation: SUCCESS ✅"