name: Code Quality Check

on:
  workflow_call:

jobs:
  format-and-lint:
    name: Format and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      
      - name: Show Tool Versions
        run: |
          dart --version
      
      - name: Install dependencies
        run: dart pub get
        
      - name: Run Dart Format Check
        run: |
          dart format --set-exit-if-changed .
        
      - name: Run Dart Analyze
        run: |
          dart analyze
      
      - name: Check for changes after formatting
        run: |
          git diff --exit-code || { echo "コードフォーマットの問題が見つかりました。ローカルで 'dart format .' を実行し、変更をコミットしてください。"; exit 1; } 