name: Run Integration Tests

on:
  workflow_call:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
          
      - name: Install dependencies
        run: dart pub get
        
      - name: Set shell script permissions
        run: chmod +x app-icon-gen.sh
        
      - name: Verify iOS Icon Output
        id: test_ios
        continue-on-error: true
        run: |
          # iOSアイコン生成の検証
          ./app-icon-gen.sh -p ios assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/ios" ]; then
            echo "Error: iOS output directory was not created"
            exit 1
          fi
          
          # Contents.jsonのチェック
          if [ ! -f "output/ios/AppIcon.appiconset/Contents.json" ]; then
            echo "Error: iOS Contents.json was not created"
            exit 1
          fi
          
          echo "iOS icon generation: SUCCESS ✅"
          >> integration_test_results.txt 2>&1 || echo "iOS icon generation: FAILED ❌" >> integration_test_results.txt

      - name: Verify Android Icon Output
        id: test_android
        continue-on-error: true
        run: |
          # Androidアイコン生成の検証
          ./app-icon-gen.sh -p android assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/android" ]; then
            echo "Error: Android output directory was not created"
            exit 1
          fi
          
          # mipmapディレクトリのチェック
          if [ ! -d "output/android/mipmap-mdpi" ]; then
            echo "Error: Android mipmap directories were not created"
            exit 1
          fi
          
          echo "Android icon generation: SUCCESS ✅"
          >> integration_test_results.txt 2>&1 || echo "Android icon generation: FAILED ❌" >> integration_test_results.txt

      - name: Verify watchOS Icon Output
        id: test_watchos
        continue-on-error: true
        run: |
          # watchOSアイコン生成の検証
          ./app-icon-gen.sh -p watchos assets/icon_gen_sample.png
          
          # 出力ディレクトリチェック
          if [ ! -d "output/watchos" ]; then
            echo "Error: watchOS output directory was not created"
            exit 1
          fi
          
          # Contents.jsonのチェック
          if [ ! -f "output/watchos/AppIcon.appiconset/Contents.json" ]; then
            echo "Error: watchOS Contents.json was not created"
            exit 1
          fi
          
          echo "watchOS icon generation: SUCCESS ✅"
          >> integration_test_results.txt 2>&1 || echo "watchOS icon generation: FAILED ❌" >> integration_test_results.txt

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: integration_test_results.txt

      - name: Check test outcomes
        if: steps.test_ios.outcome == 'failure' || steps.test_android.outcome == 'failure' || steps.test_watchos.outcome == 'failure'
        run: exit 1

      - name: Clean up
        run: rm -rf ./output 